# Generated by Django 4.0.8 on 2022-11-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
