# Generated by Django 4.0.8 on 2022-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='project',
            name='team_for_project',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
