# Generated by Django 4.0.8 on 2022-11-24 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_budget_and_more'),
    ]

    operations = [
    ]
