# Generated by Django 4.0.1 on 2023-01-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_task_slug_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Mediocre'), ('3', 'Hard')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Mediocre'), ('3', 'Hard')], default=1, max_length=7),
        ),
    ]
