# Generated by Django 3.0.8 on 2023-01-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20230131_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Working'), ('2', 'Stuck'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Working'), ('2', 'Stuck'), ('3', 'Done')], default=1, max_length=7),
        ),
    ]
