# Generated by Django 3.0.8 on 2023-02-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20230131_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
    ]
