# Generated by Django 3.0.8 on 2023-02-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_team_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(to='projects.Team'),
        ),
    ]
