# Generated by Django 3.0.8 on 2023-02-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20230204_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=80),
        ),
    ]
