# Generated by Django 4.0.1 on 2023-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_project_efforts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.FileField(default='.', upload_to=''),
        ),
    ]
