# Generated by Django 4.0.1 on 2023-02-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_documents'),
        ('projects', '0024_projectcomment'),
    ]

    operations = [
    ]
