<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-02-21 03:48
=======
# Generated by Django 4.0.1 on 2023-02-20 14:12
>>>>>>> 8c60600770f97ce215616118a91193f660dd4b6d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_documents'),
        ('projects', '0024_projectcomment'),
    ]

    operations = [
    ]
