# Generated by Django 4.1.5 on 2023-02-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_documents'),
        ('projects', '0024_projectcomment'),
    ]

    operations = [
    ]
