# Generated by Django 3.0.8 on 2023-02-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectcomment'),
        ('projects', '0024_project_documents'),
    ]

    operations = [
    ]
