# Generated by Django 3.0.8 on 2023-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_merge_20230220_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='documents/'),
        ),
    ]
