<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-02-21 03:51
=======
# Generated by Django 4.0.1 on 2023-02-20 14:12
>>>>>>> 8c60600770f97ce215616118a91193f660dd4b6d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_merge_0024_project_documents_0024_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='documents/'),
        ),
    ]
