# Generated by Django 4.0.1 on 2023-02-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_documents'),
        ('projects', '0027_auto_20230220_1840'),
    ]

    operations = [
    ]
