# Generated by Django 4.0.1 on 2023-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20230221_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='documents/'),
        ),
    ]
