# Generated by Django 4.1.7 on 2023-02-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_project_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
