# Generated by Django 4.1.7 on 2023-03-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.DeleteModel(
            name='Csv',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
