# Generated by Django 4.1.5 on 2023-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_remove_comment_parent_remove_comment_task_delete_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('1', 'Extension Based'), ('2', 'Functional Based'), ('3', 'Research Based'), ('3', 'Government')], default=1, max_length=15),
        ),
    ]
