# Generated by Django 4.1.7 on 2023-03-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
