# Generated by Django 4.1.2 on 2023-03-11 18:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_category'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Csv',
        # ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('1', 'Extension Based'), ('2', 'Functional Based'), ('3', 'Research Based'), ('3', 'Government')], default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectcomment'),
        ),
    ]
