# Generated by Django 4.0.1 on 2023-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_alter_project_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='refdocuments',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='documents/'),
        ),
    ]
