# Generated by Django 4.1.7 on 2023-03-25 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_refdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='task',
            name='hours_required',
            field=models.FloatField(default=1, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
