# Generated by Django 4.0.1 on 2023-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_remove_task_difficulty_task_hours_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dead_line',
        ),
    ]
