# Generated by Django 4.0.1 on 2023-03-28 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_remove_project_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dead_line',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
