# Generated by Django 4.0.1 on 2023-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_project_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(blank=True, to='projects.Team'),
        ),
    ]
