# Generated by Django 4.1.2 on 2023-04-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_project_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('1', 'Extension Based'), ('2', 'Functional Based'), ('3', 'Research Based'), ('4', 'Government')], default=1, max_length=15),
        ),
    ]
