# Generated by Django 4.0.1 on 2023-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamrecommender', '0004_auto_20230131_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
