# Generated by Django 3.0.8 on 2023-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamrecommender', '0009_alter_userindex_id_alter_userscore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindex',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
