# Generated by Django 4.0.8 on 2022-11-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'val_users',
            },
        ),
        migrations.CreateModel(
            name='HourVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('hours_claimed', models.IntegerField()),
                ('date_claimed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('incharge_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('team_for_project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignInInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'signin_users',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_member', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Sr Intern', 'Sr Intern'), ('Professor', 'Professor'), ('Lead Consultant', 'Lead Consultant'), ('Head Consultant', 'Head Consultant')], default='Intern', max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
