# Generated by Django 4.0.8 on 2022-11-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
