# Generated by Django 4.0.8 on 2022-12-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0002_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
