# Generated by Django 4.0.1 on 2023-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminvalidation',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
