# Generated by Django 3.0.8 on 2023-01-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0004_adminvalidation_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
