# Generated by Django 4.0.1 on 2023-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0005_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourval',
            name='date_claimed',
        ),
        migrations.RemoveField(
            model_name='hourval',
            name='team',
        ),
    ]
