# Generated by Django 4.0.1 on 2023-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0006_remove_hourval_date_claimed_remove_hourval_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminvalidation',
            name='freehours',
            field=models.IntegerField(default=0),
        ),
    ]
