# Generated by Django 4.0.1 on 2023-01-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0007_adminvalidation_freehours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminvalidation',
            name='freehours',
        ),
    ]
