# Generated by Django 4.1.7 on 2023-02-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0010_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
