# Generated by Django 4.0.1 on 2023-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0014_hourval_descrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourval',
            old_name='descrption',
            new_name='description',
        ),
    ]
