# Generated by Django 4.0.1 on 2023-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0016_requestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='requestmsg',
            field=models.CharField(max_length=1000),
        ),
    ]
