# Generated by Django 4.1.7 on 2023-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0017_alter_requestmodel_requestmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminvalidation',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
