# Generated by Django 4.1.7 on 2023-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0019_alter_adminvalidation_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvalidation',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images\\profile_pics\\default.jpg', upload_to='images/profile_pics/'),
        ),
    ]
