# Generated by Django 4.0.1 on 2023-04-10 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0021_alter_adminvalidation_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='reqdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 39, 11, 405727), max_length=100),
        ),
    ]
