# Generated by Django 4.1.2 on 2023-04-10 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0022_requestmodel_reqdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='reqdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 23, 0, 30, 632106), max_length=100),
        ),
    ]
