# Generated by Django 4.1.2 on 2023-04-13 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy2', '0029_alter_requestmodel_reqdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='reqdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 17, 23, 33, 626271), max_length=100),
        ),
    ]
