# Generated by Django 4.1.5 on 2023-02-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinance',
            name='project_id',
        ),
    ]
