# Generated by Django 4.0.1 on 2023-02-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20230221_1227'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectfinance',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
