# Generated by Django 4.0.1 on 2023-02-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_documents'),
        ('finance', '0002_finance_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='project_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
