# Generated by Django 4.0.1 on 2023-02-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20230221_1227'),
        ('finance', '0002_alter_projectfinance_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFinance',
            new_name='Finance',
        ),
    ]
