# Generated by Django 4.1.2 on 2023-02-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financemodel_delete_projectfinance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceModel',
        ),
    ]
