# Generated by Django 4.0.1 on 2023-02-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20230221_1227'),
        ('finance', '0003_rename_projectfinance_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_received', models.FloatField(default=0)),
                ('cu_percentage', models.FloatField(default=0)),
                ('expenses', models.JSONField()),
                ('income', models.JSONField()),
                ('net_amt', models.FloatField(default=0)),
                ('professor', models.JSONField()),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
