# Generated by Django 4.0.1 on 2023-02-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_finance_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='project_id',
        ),
    ]
