# Generated by Django 4.1.2 on 2023-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceModel',
        ),
    ]
