# Generated by Django 4.1.5 on 2023-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemodel',
            name='expenses',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='income',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='professor',
            field=models.JSONField(blank=True),
        ),
    ]
