# Generated by Django 4.0.1 on 2023-02-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_finance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
