# Generated by Django 4.1.5 on 2023-02-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_delete_finance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceModel',
        ),
    ]
