# Generated by Django 4.1.5 on 2023-03-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_financemodel_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financemodel',
            old_name='amt_received',
            new_name='amtreceived',
        ),
        migrations.RenameField(
            model_name='financemodel',
            old_name='cu_percentage',
            new_name='cupercentage',
        ),
    ]
