# Generated by Django 4.0.8 on 2022-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_member', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Sr Intern', 'Sr Intern'), ('Professor', 'Professor'), ('Lead Consultant', 'Lead Consultant'), ('Head Consultant', 'Head Consultant')], default='Intern', max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
