# Generated by Django 4.0.8 on 2022-12-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_hourval_alter_invite_invited_alter_invite_inviter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
