# Generated by Django 4.0.1 on 2023-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='register.UserProfile'),
        ),
    ]
