# Generated by Django 3.0.8 on 2023-01-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social_name',
        ),
    ]
