# Generated by Django 4.0.1 on 2023-01-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_remove_company_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='register.UserProfile'),
        ),
    ]
