# Generated by Django 3.0.8 on 2023-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_alter_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='register.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
