# Generated by Django 4.0.1 on 2023-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20230204_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='register.UserProfile'),
        ),
    ]
