# Generated by Django 3.0.8 on 2023-02-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='register.UserProfile'),
        ),
    ]
