# Generated by Django 4.0.1 on 2023-02-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_alter_userprofile_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
