# Generated by Django 3.0.8 on 2023-02-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_initial'),
        ('register', '0027_auto_20230213_1129'),
    ]

    operations = [
    ]
