<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-02-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20230213_1129'),
        ('register', '0029_initial'),
    ]

    operations = [
    ]
||||||| acaef2e
=======
# Generated by Django 4.0.1 on 2023-02-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20230213_1129'),
        ('register', '0029_initial'),
    ]

    operations = [
    ]
>>>>>>> 92396d7b5529fef2be59f2e626eb2f759e3f5d29
