# Generated by Django 4.1.2 on 2023-02-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20230213_1129'),
        ('register', '0029_initial'),
    ]

    operations = [
    ]
