# Generated by Django 3.0.8 on 2023-02-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_merge_20230214_2102'),
        ('register', '0030_merge_0027_auto_20230213_1129_0029_initial'),
    ]

    operations = [
    ]
