# Generated by Django 4.1.5 on 2023-02-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_merge_0027_auto_20230213_1129_0029_initial'),
        ('register', '0030_merge_20230214_2102'),
    ]

    operations = [
    ]
