# Generated by Django 4.0.1 on 2023-02-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_merge_20230220_1223'),
        ('register', '0031_merge_20230220_1942'),
        ('register', '0031_merge_20230221_0918'),
    ]

    operations = [
    ]
