# Generated by Django 4.1.7 on 2023-04-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
